Use spotless for reformatting

diff --git a/.github/workflows/daily.yml b/.github/workflows/daily.yml
--- a/.github/workflows/daily.yml
+++ b/.github/workflows/daily.yml
@@ -8,8 +8,8 @@ on:
   schedule:
     - cron: '0 11 * * *'
   pull_request:
-    branches: [main]
-    paths: [.github/workflows/daily.yml]
+    branches: [ main ]
+    paths: [ .github/workflows/daily.yml ]
   workflow_dispatch:
 
 permissions:
@@ -31,14 +31,14 @@ jobs:
       matrix:
         # tragically, there isn't a nice way to dynamically build this list...
         runner:
-          - [self-hosted, cs-reed-02]
-          - [self-hosted, cs-reed-03]
-          - [self-hosted, cs-reed-04]
-          - [self-hosted, cs-reed-05]
-          - [self-hosted, cs-reed-06]
-          - [self-hosted, cs-reed-07]
-          - [self-hosted, SJSU-office]
-          - [ubuntu-latest]
+          - [ self-hosted, cs-reed-02 ]
+          - [ self-hosted, cs-reed-03 ]
+          - [ self-hosted, cs-reed-04 ]
+          - [ self-hosted, cs-reed-05 ]
+          - [ self-hosted, cs-reed-06 ]
+          - [ self-hosted, cs-reed-07 ]
+          - [ self-hosted, SJSU-office ]
+          - [ ubuntu-latest ]
     outputs:
       # i was hoping that we could make use of these outputs, but they don't
       # get aggregated properly to be useful :'( it was hard to figure out
@@ -56,17 +56,17 @@ jobs:
         if: contains(matrix.runner, 'ubuntu-latest') == false
         id: started
         run: |
-            echo "started='${{ matrix.runner[1] }}'" >> $GITHUB_OUTPUT
-            if adb devices | grep "emulator"
-            then
-                echo "Emulator already running."
-            else
-                echo "Starting emulator..."
-                set +e
-                sudo chmod o+r,o+w /dev/kvm
-                set -e
-                nohup emulator -avd test_avd-33 -no-window -no-audio -gpu swiftshader_indirect -no-snapshot -wipe-data > /tmp/emulator.log 2>&1 &
-            fi
+          echo "started='${{ matrix.runner[1] }}'" >> $GITHUB_OUTPUT
+          if adb devices | grep "emulator"
+          then
+              echo "Emulator already running."
+          else
+              echo "Starting emulator..."
+              set +e
+              sudo chmod o+r,o+w /dev/kvm
+              set -e
+              nohup emulator -avd test_avd-33 -no-window -no-audio -gpu swiftshader_indirect -no-snapshot -wipe-data > /tmp/emulator.log 2>&1 &
+          fi
 
       - name: Checkout
         if: contains(matrix.runner, 'ubuntu-latest') == false
@@ -75,39 +75,39 @@ jobs:
       - name: Maven install
         if: contains(matrix.runner, 'ubuntu-latest') == false
         run: |
-            mkdir -p ~/.m2
-            echo "<settings>
-              <servers>
-                <server>
-                  <id>github</id>
-                  <username>github-actions[bot]</username>
-                  <password>${{ secrets.GITHUB_TOKEN }}</password>
-                </server>
-              </servers>
-            </settings>" > ~/.m2/settings.xml
-            mvn -T 1.5C -ntp install
+          mkdir -p ~/.m2
+          echo "<settings>
+            <servers>
+              <server>
+                <id>github</id>
+                <username>github-actions[bot]</username>
+                <password>${{ secrets.GITHUB_TOKEN }}</password>
+              </server>
+            </servers>
+          </settings>" > ~/.m2/settings.xml
+          mvn -T 1.5C -ntp install
 
       - name: Gradle connected tests
         if: contains(matrix.runner, 'ubuntu-latest') == false
         id: finished
         run: |
-            if adb devices | grep "emulator"
-            then
-                echo "Emulator already running."
-                set +e
-                # we don't want to immediately fail on an error since we want to
-                # collect the logs and print those before we exit with the actual
-                # exit code
-                (cd AndroidApps; DEFAULT_JVM_OPTS='"-Xmx16g" "-Xms16g"' ./gradlew connectedDebugAndroidTest --parallel)
-                TEST_RESULT=$?
-                set -e
-                adb logcat -s TestRunner -d
-                echo "finished=$TEST_RESULT" >> $GITHUB_OUTPUT
-                exit $TEST_RESULT
-            else
-                echo "Emulator not running"
-                exit 1
-            fi
+          if adb devices | grep "emulator"
+          then
+              echo "Emulator already running."
+              set +e
+              # we don't want to immediately fail on an error since we want to
+              # collect the logs and print those before we exit with the actual
+              # exit code
+              (cd AndroidApps; DEFAULT_JVM_OPTS='"-Xmx16g" "-Xms16g"' ./gradlew connectedDebugAndroidTest --parallel)
+              TEST_RESULT=$?
+              set -e
+              adb logcat -s TestRunner -d
+              echo "finished=$TEST_RESULT" >> $GITHUB_OUTPUT
+              exit $TEST_RESULT
+          else
+              echo "Emulator not running"
+              exit 1
+          fi
 
       - name: Fail after 15 minutes
         # this runner just waits for 15 minutes to fail. it is the only thing
@@ -116,19 +116,19 @@ jobs:
         if: contains(matrix.runner, 'ubuntu-latest')
         id: timeout
         run: |
-             # check every 10 seconds 90 times for queued hosts
-             for i in {0..90}
-             do
-                 curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-                 -H "Accept: application/vnd.github+json" \
-                  "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs?per_page=100" > results
-                queued=$(jq '[.jobs[] | select(.status == "queued")] | length' results)
-                if [[ "$queued" == 0 ]]
-                then
-                    exit 0
-                fi
-                sleep 10
-             done
-             echo "timeout=TIMEOUT" >> $GITHUB_OUTPUT
-             exit 1
+          # check every 10 seconds 90 times for queued hosts
+          for i in {0..90}
+          do
+              curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              -H "Accept: application/vnd.github+json" \
+               "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs?per_page=100" > results
+             queued=$(jq '[.jobs[] | select(.status == "queued")] | length' results)
+             if [[ "$queued" == 0 ]]
+             then
+                 exit 0
+             fi
+             sleep 10
+          done
+          echo "timeout=TIMEOUT" >> $GITHUB_OUTPUT
+          exit 1
 
